package functions

// FuncNames defines the set of available function names available to the CLI
var FuncNames = []string{
        "BandwidthMonitor",
	"BroadbandProductType",
	"DataPumpVersion",
	"DataReceived",
	"DataSent",
        "DhcpAuthoritative",
	"DhcpPoolStart",
	"DhcpPoolEnd",
	"DhcpSubnetMask",
	"DownstreamSyncSpeed",
	"EnableDebug",
	"EventLog",
	"HardwareVersion",
	"InternetConnectionStatus",
	"LightStatus",
	"LocalTime",
	"MaintenaceFirmwareVersion",
	"PublicIPAddress",
	"PublicSubnetMask",
	"Reboot",
	"SambaIP",
	"SambaHost",
	"SerialNumber",
	"SoftwareVersion",
	"UpstreamSyncSpeed",
	"Version",
	"WiFiSecurityMode",
	"WiFiSSID"}
